### ISSUE TITLE
isPointerOverScrollbar Error

### ISSUE THREAD

**Issue by vinnchan** [jakebonk/FlutterBoardView#15]
my yaml file:
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  boardview: ^0.2.1

When I flutter run 
../../developer/flutter/.pub-cache/hosted/pub.dartlang.org/boardview-0.2.2/lib/vs_scrollbar.dart:321:31: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.                            
    if (isPointerOverScrollbar(event.position,PointerDeviceKind.mouse)) {

**Comment by selmaskopljakovic** [comment]
How to resolve this?

**Comment by MinSomai** [comment]
> How to resolve this?

Hey @selmaskopljakovic ! This is a temporary solution I'm using. I've forked the boardview and updated vs_scrollbar package.

```
dependencies:
  flutter:
    sdk: flutter

  boardview:
    git:
      url: https://github.com/MinSomai/FlutterBoardView.git
      ref: master
```
